name: cmake

env:
    CMAKE_BUILD_PARALLEL_LEVEL: 2
    CTEST_PARALLEL_LEVEL: 2

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/cmake-gfortran.yml"


jobs:

  linux-openmpi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install prereqs
      run: |
        sudo apt -yq update
        sudo apt -yq install --no-install-recommends libopenmpi-dev libcoarrays-dev libcoarrays-openmpi-dev

    - name: CMake configure
      run: cmake --preset default
    - name: configure log
      if: ${{ failure() }}
      run: cat build/CMakeFiles/CMakeError.log

    - run: cmake --build --preset default
    - run: ctest --preset default

  linux-mpich:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install prereqs
      run: |
        sudo apt -yq update
        sudo apt -yq install --no-install-recommends libmpich-dev

    - name: CMake configure
      run: cmake --preset default
    - name: configure log
      if: ${{ failure() }}
      run: cat build/CMakeFiles/CMakeError.log

    - run: cmake --build --preset default
    - run: ctest --preset default

# MacOS CI MPI tests can hang, so skip. They work find on regular physical Macs.

  mac-openmpi:
    needs: linux-openmpi
    runs-on: macos-latest
    env:
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v2

    - name: install prereqs
      run: brew install openmpi

    - name: CMake configure
      run: cmake --preset default
    - name: configure log
      if: ${{ failure() }}
      run: cat build/CMakeFiles/CMakeError.log

    - run: cmake --build --preset default

  mac-mpich:
    needs: linux-mpich
    runs-on: macos-latest
    env:
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v2

    - name: install prereqs
      run: brew install mpich

    - name: CMake configure
      run: cmake --preset default
    - name: configure log
      if: ${{ failure() }}
      run: cat build/CMakeFiles/CMakeError.log

    - run: cmake --build --preset default
